# NOTE: apt-get install build-essential contains required compilers on debian
---
name: glacierhack
channels:
        - conda-forge

dependencies:
        - python=3.6
        - gdal>=2.2.3
        - rasterio>=1.0
        - cython
        - jupyter
        - matplotlib
        - numpy
        - pyproj
        - shapely
        - ffmpeg
        - pip:
            - pygeotools
            - pygeoprocessing
